server:
  port: 8082
spring:
  jpa:
    database: h2
    open-in-view: false
  datasource:
    url: jdbc:h2:~/topic_db
    driver-class-name: org.h2.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
  application:
    name: topic-service

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    service-url:
      defaultZone: http://fduse:Fudanse2019@eureka-service:8911/eureka/
    register-with-eureka: true
    fetch-registry: true